is.num = (arg) => typeof arg === "number",
is.nan = (arg) => isNaN(arg),
is.str = (arg) => typeof arg === "string",
is.bool = (arg) => typeof arg === "boolean",
is.undef = (arg) => typeof arg === "undefined",
is.def = (arg) => typeof arg !== "undefined",
is.arr = (arg) => Array.isArray(arg),
is.obj = (arg) => Object.prototype.toString.call(arg) === "[object Object]",
is.fun = (arg) => Object.prototype.toString.call(arg) === "[object Function]",
is.truthy = (arg) => arg ? true : false,
is.falsy = (arg) => !arg ? true : false